apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-deployment
  labels:
    app: echo-app
spec:
  serviceName: "echo-replica"
  replicas: 3
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: echo-app
          image: einavl/echorep:13
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
